


minio:
  endpoint: 172.16.2.89
  port: 9000
  accessKey: HYAoMMdtPyzJhzdX2Ufu
  secretKey: 25nLQo4I5lBQYf0szW36TWfUVGZtNVxepVlCvECW
  bucketName: myio
  defaultBucketName: myio
  secure: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    cn.dhx.boot.dao: debug