aa:
  bb: 测试我的
  cc: false
server:
  port: 8001

#k:
#  k1: v1
#  k2: v2
#  k3: v3
maps: "{'key1': 'value1', 'key2': 'value2'}"


#maps: "{key1: 'value1', key2: 'value2'}"


hashmap: '{
  "key1":"value1",
  "key12":"value12"
}'

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#   health:
#    show-details: always
ftp:
  host: 127.0.0.1




jasypt:
  encryptor:
    password: 28a39946-bf3e-42b9-a2e6-5de7c5040f14
