aa:
  bb: 测试我的
  cc: false
server:
  port: 8001

#k:
#  k1: v1
#  k2: v2
#  k3: v3
maps: "{'key1': 'value1', 'key2': 'value2'}"


#maps: "{key1: 'value1', key2: 'value2'}"

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#   health:
#    show-details: always
ftp:
  host: 127.0.0.1